apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - collector-rbac.yaml
  - collector-configmap.yaml
  - collector.yaml
  - orders.yaml
  - gateway.yaml
  - fulfillment.yaml
  - podmonitoring.yaml
